In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("../data/cleaned_superstore_data.csv",parse_dates=['order_date', 'ship_date'])

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 31 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   category           51290 non-null  object
 1   city               51290 non-null  object
 2   country            51290 non-null  object
 3   customer_id        51290 non-null  object
 4   customer_name      51290 non-null  object
 5   discount           51290 non-null  float64
 6   market             51290 non-null  object
 7   order_date         51290 non-null  datetime64[ns]
 8   order_id           51290 non-null  object
 9   order_priority     51290 non-null  object
 10  product_id         51290 non-null  object
 11  product_name       51290 non-null  object
 12  profit             51290 non-null  float64
 13  quantity           51290 non-null  int64
 14  region             51290 non-null  object
 15  sales              51290 non-null  int64
 16  segment            51290 non-null  object
 17  ship_date          51290 non-null  datetime64[ns]
 18  ship_mode          51290 non-null  object
 19  shipping_cost      51290 non-null  float64
 20  state              51290 non-null  object
 21  sub_category       51290 non-null  object
 22  order_year         51290 non-null  int64
 23  order_month        51290 non-null  int64
 24  order_quarter      51290 non-null  int64
 25  order_day_of_week  51290 non-null  int64
 26  is_weekend         51290 non-null  int64
 27  order_week         51290 non-null  int64
 28  discount_bin       51290 non-null  object
 29  profit_margin      51289 non-null  float64
 30  sales_per_unit     51290 non-null  float64
dtypes: datetime64[ns](2), float64(5), int64(8), object(16)
memory usage: 12.1+ MB

# Total profit

In [13]:
df['profit'].sum()

1467457.2912800002

# Total sales

In [10]:
df['sales'].sum()

12642905

# Profit margin

In [8]:
(df['profit'].sum() / df['sales'].sum() )* 100

11.606962887722403

# Total orders

In [11]:
df['order_id'].nunique()

25035

# Total customers

In [12]:
df['customer_id'].nunique()

4873

# Average order value

In [16]:
(df['sales'].sum() /df['order_id'].nunique())

505.0091871380068

# Sales and Profit by category

In [17]:
df.groupby(df['category'])[['sales','profit']].sum().sort_values(by ='sales' , ascending = False)

                   sales        profit
category
Technology       4744691  663778.73318
Furniture        4110884  285204.72380
Office Supplies  3787330  518473.83430

# Sales and Profit by region

In [18]:
df.groupby(df['region'])[['sales','profit']].sum().sort_values(by ='sales' , ascending = False)

                  sales        profit
region
Central         2822399  311403.98164
South           1600960  140355.76618
North           1248192  194597.95252
Oceania         1100207  120089.11200
Southeast Asia   884438   17852.32900
North Asia       848349  165578.42100
Emea             806184   43897.97100
Africa           783776   88871.63100
Central Asia     752839  132480.18700
West             725514  108418.44890
East             678834   91522.78000
Caribbean        324281   34571.32104
Canada            66932   17817.39000

# Yearly Sales Growth

In [19]:
 df.groupby(df['order_date'].dt.year)['sales'].sum()

order_date
2011    2259511
2012    2677493
2013    3405860
2014    4300041
Name: sales, dtype: int64